"use client";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { useEffect } from "react";
import { usePathname } from "next/navigation";
import ProfileHeader from "../newuser/components/header/ProfileHeader"
// import Sidebar from "./components/sidebar/Sidebar";
import Sidebar from "@/components/Sidebar";
import AboutUser from "./components/sections/aboutUser/AboutUser"
import Post from "../newuser/components/sections/posts/Posts"
import WorkExperience from "../newuser/components/sections/workExperience/WorkExperience"
import Education from "../newuser/components/sections/education/Education"
import AwardsAndCertifications from "../newuser/components/sections/awardsAndCertifications/AwardsAndCertifications"
import FeaturedVideos from "../newuser/components/sections/featuredVideos/FeaturedVideos"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function ParticipantLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  // Ensure page always starts from the top
  useEffect(() => {
    window.scrollTo(0, 0);
  }, [pathname]);
  const isNotificationsPage = pathname === '/participant/notifications';
  const isEventsPage = pathname === '/participant/events' || pathname.startsWith('/participant/events/');
  const isProfilePage = pathname === '/participant' || pathname === '/participant/';

  return (
    <div className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <ProfileHeader />
      <div className="flex flex-col lg:flex-row items-stretch justify-between min-h-screen">
        <Sidebar />
        <div className="w-full bg-[#fffbf5] ml-64">
          {isNotificationsPage ? (
            // Notifications Page - Full width
            <div className="min-h-screen">
              {children}
            </div>
          ) : isEventsPage ?  (
            <div className="min-h-screen">
              {children}
            </div>
          ) : isProfilePage ? (
          <main className="flex flex-col items-center justify-between gap-5 py-5 px-4 lg:px-0">
            <AboutUser />
            <Post />
            <WorkExperience />
            <Education />
            <AwardsAndCertifications />
            <FeaturedVideos />
          </main>) : (
            <div className="min-h-screen">
              {/* {children} */}
            </div>
          )
          }
        </div>
      </div>
    </div>
  );
}

